### ISSUE TITLE
Some minor issues

### ISSUE THREAD

**Issue by bjarnef** [bomortensen/Our.Umbraco.OpeningHours#3]
* There are duplicates of `opens` and `closes` in da-DK.xml and en-GB.xml
https://goo.gl/oEEiOk
https://goo.gl/rFC6YR

* Make a copy of en-GB.xml and name it en-US.xml
* For time picker consider to use `icon-time` instead: https://goo.gl/C0nVrL
* In package.manifest maybe define a `group` and `ìcon`: https://goo.gl/bbbdNb - https://goo.gl/jv8Xvc
* In css use a unique css class on top level https://goo.gl/EED42f  ... it can be defined here https://goo.gl/BdL8X2 .. otherwise it might conflict with styling of other property editors or core styling.

**Comment by abjerner** [comment]
Thanks. I will look into that ;)

**Comment by bjarnef** [comment]
Great!
As soon you have a working build (like a beta version), can you add it to https://our.umbraco.org/projects/backoffice-extensions/ourumbracoopeninghours/ so it is not just an empty project?

**Comment by abjerner** [comment]
I wasn't really sure whether the Our project was public or not, but yes, doing a pre-release should be possible as well ;)

**Comment by abjerner** [comment]
The progress so far:

1. The duplicates in the language files have now been removed.

2. The language file for `en-GB` has now been copied to `en-US`.

3. The time picker appears to be a dropdown rather than an actual picker as shown on the screenshot. I'll need to look into that.

4. Both `icon` and `group` have now been specified for all three property editors in `package.manifest`.

5. I'll need to look into the CSS as well. It would indeed make sense to have a unique class name.

6. I've pushed a pre-release to [NuGet](https://www.nuget.org/packages/Our.Umbraco.OpeningHours/1.0.0-beta1), [GitHub](https://github.com/bomortensen/Our.Umbraco.OpeningHours/releases/tag/v1.0.0-beta1) and [Our Umbraco](https://our.umbraco.org/projects/backoffice-extensions/ourumbracoopeninghours/).

I'll look into _3._ and _5._ as well as doing some more testing in the coming days, and hopefully be able to release the first stable release :smile:

**Comment by bjarnef** [comment]
Great work @abjerner 
I just tested the pre-release of the package.. it seems it refer to some missing keys?

![image](https://cloud.githubusercontent.com/assets/2919859/14590451/e8e68604-04fa-11e6-8109-e49977ca8ffb.png)

Furthermore when adding a holiday opening hour the date in "invalid date" instead of just empty/null.

For timepicker it can use the datepicker in core with pickTime = true and pickDate = false ... or like in the OpeningSoon package - I think it use this plugin: http://jonthornton.github.io/jquery-timepicker/

**Comment by bjarnef** [comment]
Ahh, as I remember this wont work: https://github.com/bomortensen/Our.Umbraco.OpeningHours/blob/master/src/Our.Umbraco.OpeningHours/App_Plugins/OpeningHours/views/openingHours.html#L22

Instead you need to create a property in scope from controller and use localizationService.

**Comment by bjarnef** [comment]
@abjerner maybe you want to use this timepicker?
http://angularscript.com/simple-time-picker-for-angularjs-fm-timepicker/

**Comment by abjerner** [comment]
@bjarnef What version of Umbraco are you using? And what culture? All translations work in my test solution (7.4) for both `da-DK` and `en-GB`. The files are however copied to by test solution using Grunt tasks, so there is a chance that I somehow messed up in the NuGet release.

**Comment by bjarnef** [comment]
@abjerner clean Umbraco 7.4.3 install (but also tested on 7.4.2). Using default culture `en-GB`

In this PR https://github.com/umbraco/Umbraco-CMS/pull/766/files I tried for localization of help section to use a scope property as key in localize directive in view, but didn't work (see comment from Shannon).

The "holiday" title does not work, because the keys are not matching :)
https://github.com/bomortensen/Our.Umbraco.OpeningHours/blob/master/src/Our.Umbraco.OpeningHours/App_Plugins/OpeningHours/lang/en-GB.xml#L7

**Comment by abjerner** [comment]
@bjarnef thanks for the further info :smile:

For the weekdays not showing up, this was a problem in the controller when initializing the property editor with an empty model (eg. on a new page). This was fixed in 3725780b13e0c07491274e50cebacb36da49a9b8.

From what I can tell the `localize` element works fine with setting `key` to an Angular variable. At least my weekdays are displayed Danish.

Te key `holidaysTitle` has now been corrected to `holidayTitle`. This only affected the English language files, so I had missed it since I primarily tested with the Danish language file.

Since this issue contains multiple issues (again, thanks for reporting), I have taken the liberty to add the [time picker](https://github.com/bomortensen/Our.Umbraco.OpeningHours/issues/6) and [CSS class name](https://github.com/bomortensen/Our.Umbraco.OpeningHours/issues/7).

As far as I can tell, all other issues mentioned here are now fixed?

**Comment by bjarnef** [comment]
Okay, thanks for info @abjerner  ... maybe it is because string concatenation in https://github.com/bomortensen/Our.Umbraco.OpeningHours/commit/3725780b13e0c07491274e50cebacb36da49a9b8 .. and not directly a variable property into the localize key?

Thanks for opening the other issues :+1:  .. 
yes, it ended up with more than just some minor issues :see_no_evil:

Let's close this one and open new ones :ok_hand:
